#!/usr/bin/env python3
"""Generate search-index.json for The Gig Ledger from the article HTML files.

Extracts per article: title (h1, falling back to <title>), url
("articles/<slug>.html"), excerpt (first ~160 chars of the first
substantive paragraph), and a list of h2 headings.

Usage: python3 tools/gen_search_index.py
"""
import json
import os
import re
import sys
from html.parser import HTMLParser

SITE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARTICLES_DIR = os.path.join(SITE_ROOT, "articles")
OUT_PATH = os.path.join(SITE_ROOT, "search-index.json")

SKIP_HEADINGS = {"faq", "keep reading"}


class ArticleParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.h1 = ""
        self.title_tag = ""
        self.paragraphs = []  # (class_attr, text)
        self.h2s = []
        self._capture = None  # "h1" | "title" | "p" | "h2"
        self._buf = []
        self._p_class = ""
        self._in_article = False

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == "article":
            self._in_article = True
        if tag == "h1" and not self.h1:
            self._capture = "h1"
            self._buf = []
        elif tag == "title" and not self.title_tag:
            self._capture = "title"
            self._buf = []
        elif tag == "h2" and self._in_article:
            self._capture = "h2"
            self._buf = []
        elif tag == "p" and self._in_article:
            self._capture = "p"
            self._buf = []
            self._p_class = attrs.get("class", "")

    def handle_endtag(self, tag):
        if tag == "article":
            self._in_article = False
        if tag == "h1" and self._capture == "h1":
            self.h1 = self._text()
            self._capture = None
        elif tag == "title" and self._capture == "title":
            self.title_tag = self._text()
            self._capture = None
        elif tag == "h2" and self._capture == "h2":
            text = self._text()
            if text:
                self.h2s.append(text)
            self._capture = None
        elif tag == "p" and self._capture == "p":
            text = self._text()
            if text:
                self.paragraphs.append((self._p_class, text))
            self._capture = None
            self._p_class = ""

    def handle_data(self, data):
        if self._capture:
            self._buf.append(data)

    def _text(self):
        return re.sub(r"\s+", " ", "".join(self._buf)).strip()


def build_entry(slug, path):
    with open(path, encoding="utf-8") as f:
        parser = ArticleParser()
        parser.feed(f.read())

    title = parser.h1 or parser.title_tag.replace(" — The Gig Ledger", "").strip()
    excerpt = ""
    for cls, text in parser.paragraphs:
        if "byline" in cls:
            continue
        if len(text) >= 40:
            excerpt = text
            break
    if not excerpt and parser.paragraphs:
        excerpt = parser.paragraphs[0][1]
    if len(excerpt) > 160:
        cut = excerpt[:160].rsplit(" ", 1)[0]
        excerpt = cut + "…"

    headings = [h for h in parser.h2s if h.lower() not in SKIP_HEADINGS]

    return {
        "title": title,
        "url": f"articles/{slug}.html",
        "excerpt": excerpt,
        "headings": headings,
    }


def main():
    articles = []
    for fname in sorted(os.listdir(ARTICLES_DIR)):
        if not fname.endswith(".html"):
            continue
        slug = fname[:-5]
        entry = build_entry(slug, os.path.join(ARTICLES_DIR, fname))
        if not entry["title"]:
            print(f"WARNING: no title found in {fname}", file=sys.stderr)
        articles.append(entry)

    index = {"generated_note": "Generated by tools/gen_search_index.py — do not edit by hand.",
             "articles": articles}
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=2)
        f.write("\n")

    # Validate: JSON parses and every URL resolves to a real local file.
    with open(OUT_PATH, encoding="utf-8") as f:
        loaded = json.load(f)
    missing = []
    for a in loaded["articles"]:
        local = os.path.join(SITE_ROOT, a["url"])
        if not os.path.isfile(local):
            missing.append(a["url"])
        if not a["title"] or not a["excerpt"]:
            print(f"WARNING: incomplete entry for {a['url']}", file=sys.stderr)
    if missing:
        print(f"ERROR: URLs with no local file: {missing}", file=sys.stderr)
        sys.exit(1)

    print(f"Wrote {OUT_PATH}: {len(articles)} articles, all URLs resolve.")


if __name__ == "__main__":
    main()
